/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Logins;

import javax.swing.JOptionPane;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.io.FileWriter;
import java.io.IOException;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JCheckBox;

public class Test_S extends javax.swing.JFrame {

    /**
     * Creates new form Test_S
     */
    public Test_S() {
        initComponents();
        setTitle("Hackers Nightmare");
        
    } 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTest1 = new javax.swing.JCheckBox();
        jTest2 = new javax.swing.JCheckBox();
        jbtnRun = new javax.swing.JButton();
        jbtnStop = new javax.swing.JButton();
        jbtnExit = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtResult = new javax.swing.JTextArea();
        jtxtR = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTest1.setBackground(new java.awt.Color(51, 51, 51));
        jTest1.setFont(new java.awt.Font("Calibri Light", 3, 24)); // NOI18N
        jTest1.setForeground(new java.awt.Color(204, 255, 255));
        jTest1.setText("Software Test");
        jTest1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTest1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTest1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 180, 40));

        jTest2.setBackground(new java.awt.Color(51, 51, 51));
        jTest2.setFont(new java.awt.Font("Calibri Light", 3, 24)); // NOI18N
        jTest2.setForeground(new java.awt.Color(204, 255, 255));
        jTest2.setText("System Test");
        jTest2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTest2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTest2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 180, 40));

        jbtnRun.setFont(new java.awt.Font("Calibri", 3, 36)); // NOI18N
        jbtnRun.setText("Run");
        jbtnRun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRunActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnRun, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 100, 60));

        jbtnStop.setFont(new java.awt.Font("Calibri", 3, 36)); // NOI18N
        jbtnStop.setText("Stop");
        jbtnStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnStopActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnStop, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, 110, 60));

        jbtnExit.setFont(new java.awt.Font("Calibri", 3, 36)); // NOI18N
        jbtnExit.setText("Exit");
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 560, 140, 60));

        jButton3.setFont(new java.awt.Font("Calibri", 3, 36)); // NOI18N
        jButton3.setText("Save");
        jButton3.setBounds(190, 330, 110, 50);
        jLayeredPane1.add(jButton3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jtxtResult.setBackground(new java.awt.Color(74, 150, 49));
        jtxtResult.setColumns(20);
        jtxtResult.setFont(new java.awt.Font("Calibri Light", 2, 24)); // NOI18N
        jtxtResult.setRows(5);
        jtxtResult.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Log Report", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Adobe Arabic", 2, 36), new java.awt.Color(0, 0, 0))); // NOI18N
        jScrollPane1.setViewportView(jtxtResult);

        jScrollPane1.setBounds(20, 20, 440, 300);
        jLayeredPane1.add(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        getContentPane().add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 20, 480, 390));

        jtxtR.setBackground(new java.awt.Color(10, 122, 25));
        jtxtR.setColumns(20);
        jtxtR.setFont(new java.awt.Font("Calibri Light", 2, 48)); // NOI18N
        jtxtR.setRows(5);
        jtxtR.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Testing Area", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Adobe Arabic", 2, 36), new java.awt.Color(0, 0, 0))); // NOI18N
        getContentPane().add(jtxtR, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, 1070, 210));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\prash\\Desktop\\Thematrixincode99.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1490, 768));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnStopActionPerformed
        
           jtxtR.setText("Testing to check for Hack is Stopped...");
           jtxtResult.setText("Testing is Interrupted");
           ImageIcon point = new ImageIcon("pic1.jpg");
           JOptionPane.showMessageDialog(null,"System is at Risk","Error",JOptionPane.ERROR_MESSAGE, point);
    }//GEN-LAST:event_jbtnStopActionPerformed

    private void jTest1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTest1ActionPerformed
        jTest1 = new jTest1("Software Test",true);
    }//GEN-LAST:event_jTest1ActionPerformed

    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
       
        this.dispose();
        ///System.exit(0);
    }//GEN-LAST:event_jbtnExitActionPerformed

    private void jTest2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTest2ActionPerformed
        jTest2 = new jTest2("System Test",true);
        
    }//GEN-LAST:event_jTest2ActionPerformed

    private void jbtnRunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRunActionPerformed

                 Sleeper so=new Sleeper();
                 
           // jtxtResult.setText("Software test is passed");
            
            Sleeper.timea();
            System.out.println("Software is Testing..");
             jtxtR.setText("Software is Testing...");
             
             
          Sleeper.timeb();
         // jtxtR.setText("Software is Testing...");
          jtxtR.setText("Software Test Completes...");
         
                  
          // jtxtR.setText("Software1 is Testing...");
            jtxtResult.setText("Software test is passed." );   
            
            Sleeper.timea();
            jtxtR.setText("System is Testing...");
            jtxtResult.setText("Software and System test is passed");
            
            
        
        
        
        
       // jtxtR.setText("Software is Testing...");
       // jtxtResult.setText("Software test is passed");
        //Minute.sleep(5);
       
      //  jtxtR.setText("System is Testing...");
        //jtxtResult.setText("System test is passed");
    }//GEN-LAST:event_jbtnRunActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Test_S.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Test_S.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Test_S.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Test_S.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Test_S().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox jTest1;
    private javax.swing.JCheckBox jTest2;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnRun;
    private javax.swing.JButton jbtnStop;
    private javax.swing.JTextArea jtxtR;
    private javax.swing.JTextArea jtxtResult;
    // End of variables declaration//GEN-END:variables

private void systemExit()
    {
    WindowEvent winCloseing = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
    }

    private void setText(String system_is_Testing) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void than() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private static class jTest1 extends JCheckBox {

        public jTest1(String software_Test, boolean b) {
        }
    }

    private static class jTest2 extends JCheckBox {

        public jTest2(String system_Test, boolean b) {
        }
    }

    private static class Sleeper {

        public static  void main(String[] args) {
            
        }
        private static void timea() {
           try {
               Thread.sleep(2500);
           }
           catch(Exception e){
}
           
             //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

        private static void timeb() {
           try {
               Thread.sleep(2500);
               }
           catch(Exception e){
               }
            
             //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }
    }
  }
